begin;

alter table public.gpe_challenges
  add column if not exists week_number integer,
  add column if not exists theme text,
  add column if not exists icon text,
  add column if not exists cta_label text,
  add column if not exists submission_type text,
  add column if not exists verification_method text,
  add column if not exists badge_eligible boolean not null default false,
  add column if not exists why_it_matters text,
  add column if not exists related_kind text,
  add column if not exists related_url text,
  add column if not exists is_featured boolean not null default false;

create index if not exists gpe_challenges_season_week_idx
  on public.gpe_challenges (
    season_id,
    week_number,
    display_order
  );

insert into public.gpe_action_types (slug, label, description, display_order)
values
  ('sign_petition', 'Sign Petition', 'Sign a petition or letter campaign.', 10),
  ('create_content', 'Create Content', 'Create original climate or community content.', 20),
  ('share_story', 'Share Story', 'Share a personal climate or community story.', 30),
  ('repost_gpe', 'Repost GPE', 'Amplify a GPE post or resource.', 40),
  ('recruit_friend', 'Recruit Friend', 'Invite a friend to participate.', 60),
  ('learn', 'Learn', 'Complete a learning action.', 70)
on conflict (slug) do update
set
  label = excluded.label,
  description = excluded.description,
  display_order = excluded.display_order,
  updated_at = now();

drop view if exists public.gpe_hub_camp_challenges cascade;

create view public.gpe_hub_camp_challenges as
select
  ch.*,
  at.slug as action_type_slug,
  at.label as action_type_label,
  s.slug as season_slug,
  s.name as season_name
from public.gpe_challenges ch
join public.gpe_seasons s
  on s.id = ch.season_id
left join public.gpe_action_types at
  on at.id = ch.action_type_id
where ch.is_active
  and ch.is_hub_visible
  and s.status = 'active'
  and s.is_visible;

insert into public.gpe_challenges (
  season_id,
  action_type_id,
  slug,
  title,
  short_description,
  instructions,
  category,
  point_value,
  starts_at,
  ends_at,
  is_active,
  is_public,
  is_hub_visible,
  requires_proof,
  requires_review,
  auto_approve,
  allow_multiple_submissions,
  max_completions_per_member,
  display_order,
  action_url,
  external_source,
  external_action_slug,
  week_number,
  theme,
  icon,
  cta_label,
  submission_type,
  verification_method,
  badge_eligible,
  why_it_matters,
  related_kind,
  related_url,
  is_featured
)
select
  season.id,
  action_type.id,
  seed.slug,
  seed.title,
  seed.short_description,
  seed.instructions,
  seed.category,
  seed.point_value,
  seed.starts_at::timestamptz,
  seed.ends_at::timestamptz,
  true,
  true,
  true,
  seed.requires_proof,
  true,
  false,
  false,
  1,
  seed.display_order,
  seed.action_url,
  seed.external_source,
  seed.external_action_slug,
  seed.week_number,
  seed.theme,
  seed.icon,
  seed.cta_label,
  seed.submission_type,
  seed.verification_method,
  true,
  seed.why_it_matters,
  seed.related_kind,
  seed.related_url,
  seed.is_featured
from public.gpe_seasons season
cross join (
  values
    (
      'beat-heat-extreme-weather-petition',
      'sign_petition',
      'Sign the Extreme Weather Petition',
      'Ask leaders to protect our communities from dangerous heat and extreme weather.',
      'Sign the petition, then come back to submit the challenge for Camp GPE points.',
      'sign_petition',
      1::integer,
      '2026-07-06 00:00:00-05',
      '2026-07-17 23:59:59-05',
      false,
      110,
      'https://actionnetwork.org/letters/extreme-weather-puts-our-communities-at-risk-its-time-for-bold-climate-action-2?source=GPE',
      'action_network',
      'extreme-weather-puts-our-communities-at-risk-its-time-for-bold-climate-action-2',
      1,
      'Hot Girl Summer starts with protecting our communities.',
      '☀️',
      'Open Petition',
      'petition',
      'petition_completion_or_team_review',
      'Extreme heat is a climate justice issue, and community protection starts with visible public pressure.',
      'petition',
      'https://www.girlplusenvironment.org/extreme-weather-action',
      true
    ),
    (
      'beat-heat-story-sticker',
      'repost_gpe',
      'Complete the Camp GPE Story Sticker',
      'Use the Camp GPE story sticker to invite your community into the summer challenge.',
      'Post the Camp GPE sticker to your story and submit a screenshot or link for review.',
      'repost_gpe',
      2::integer,
      '2026-07-06 00:00:00-05',
      '2026-07-17 23:59:59-05',
      true,
      120,
      null,
      null,
      null,
      1,
      'Hot Girl Summer starts with protecting our communities.',
      '📱',
      'Open Submission Flow',
      'social_link',
      'team_review',
      'Story stickers make advocacy feel easy to share and help more people find Camp GPE.',
      'submission',
      null,
      false
    ),
    (
      'beat-heat-short-video',
      'create_content',
      'Create a Short Video',
      'Make a short video about why extreme weather protection matters in your community.',
      'Create a short-form video, post or save the link, and submit it for Team GPE review.',
      'create_content',
      5::integer,
      '2026-07-06 00:00:00-05',
      '2026-07-17 23:59:59-05',
      true,
      130,
      null,
      null,
      null,
      1,
      'Hot Girl Summer starts with protecting our communities.',
      '📹',
      'Open Submission Flow',
      'video_link',
      'team_review',
      'Short videos turn climate protection into a story people can understand and share.',
      'submission',
      null,
      false
    ),
    (
      'tell-your-story-climate-story',
      'share_story',
      'Share Your Climate Story',
      'Tell people how climate change, pollution, heat, or energy costs show up in your life.',
      'Write, record, or post your story and submit the link or text for Team GPE review.',
      'share_story',
      5::integer,
      '2026-07-20 00:00:00-05',
      '2026-07-31 23:59:59-05',
      true,
      210,
      null,
      null,
      null,
      3,
      'Your story could be the reason someone takes action.',
      '📹',
      'Open Submission Flow',
      'story_link',
      'team_review',
      'Personal stories help climate action feel local, urgent, and possible.',
      'submission',
      null,
      true
    ),
    (
      'tell-your-story-camp-graphics',
      'repost_gpe',
      'Post Using Camp GPE Graphics',
      'Use Camp GPE graphics to share the challenge and invite people to act.',
      'Download or use a Camp GPE graphic, post it, and submit a screenshot or link.',
      'repost_gpe',
      2::integer,
      '2026-07-20 00:00:00-05',
      '2026-07-31 23:59:59-05',
      true,
      220,
      null,
      null,
      null,
      3,
      'Your story could be the reason someone takes action.',
      '📲',
      'Open Toolkit',
      'social_link',
      'team_review',
      'Shared graphics give members a ready-to-use way to spread the campaign.',
      'toolkit',
      null,
      false
    ),
    (
      'tell-your-story-encourage-petition-signatures',
      'recruit_friend',
      'Encourage Signatures for the Petition',
      'Ask friends, family, or followers to sign the extreme weather petition.',
      'Share the petition and submit a note, screenshot, or link showing how you encouraged signatures.',
      'recruit_friend',
      2::integer,
      '2026-07-20 00:00:00-05',
      '2026-07-31 23:59:59-05',
      true,
      230,
      'https://actionnetwork.org/letters/extreme-weather-puts-our-communities-at-risk-its-time-for-bold-climate-action-2?source=GPE',
      null,
      null,
      3,
      'Your story could be the reason someone takes action.',
      '💚',
      'Open Petition',
      'social_link',
      'team_review',
      'Recruiting signatures helps turn individual concern into collective action.',
      'petition',
      'https://www.girlplusenvironment.org/extreme-weather-action',
      false
    ),
    (
      'sign-high-energy-bills-petition',
      'sign_petition',
      'Sign the High Energy Bills Petition',
      'Tell Congress that communities need relief from high energy bills.',
      'Sign the high energy bills action, then submit the challenge for Camp GPE points.',
      'sign_petition',
      1::integer,
      '2026-08-03 00:00:00-05',
      '2026-08-14 23:59:59-05',
      false,
      310,
      'https://actionnetwork.org/letters/tell-congress-we-need-relief-from-high-energy-bills-partner/?source=GPE',
      'action_network',
      'tell-congress-we-need-relief-from-high-energy-bills-partner',
      5,
      'Everyone deserves energy that keeps us safe, not stressed.',
      '⚡',
      'Open Petition',
      'petition',
      'petition_completion_or_team_review',
      'Energy bills are part of climate justice when families have to choose between safety, comfort, and cost.',
      'petition',
      'https://www.girlplusenvironment.org/high-energy-bills-action',
      true
    ),
    (
      'energy-justice-utility-costs-video',
      'create_content',
      'Create a Video About Utility Costs',
      'Explain how high energy bills affect young people, families, or your community.',
      'Create a short video, post or save the link, and submit it for Team GPE review.',
      'create_content',
      5::integer,
      '2026-08-03 00:00:00-05',
      '2026-08-14 23:59:59-05',
      true,
      320,
      null,
      null,
      null,
      5,
      'Everyone deserves energy that keeps us safe, not stressed.',
      '📹',
      'Open Submission Flow',
      'video_link',
      'team_review',
      'A clear story about utility costs makes energy justice concrete.',
      'submission',
      null,
      false
    ),
    (
      'energy-justice-share-energy-bill-fact',
      'learn',
      'Share a Fact About Energy Bills',
      'Post or submit a fact that helps people understand energy affordability.',
      'Share a fact from a trusted source and submit the post, screenshot, or citation.',
      'learn',
      2::integer,
      '2026-08-03 00:00:00-05',
      '2026-08-14 23:59:59-05',
      true,
      330,
      null,
      null,
      null,
      5,
      'Everyone deserves energy that keeps us safe, not stressed.',
      '📱',
      'Open Submission Flow',
      'social_link',
      'team_review',
      'Facts give people language to explain why energy affordability belongs in climate advocacy.',
      'submission',
      null,
      false
    ),
    (
      'finish-strong-favorite-lesson',
      'share_story',
      'Share Your Favorite Lesson from Camp',
      'Reflect on one thing Camp GPE taught you about climate advocacy.',
      'Share a post, video, or written reflection and submit it for Team GPE review.',
      'share_story',
      5::integer,
      '2026-08-17 00:00:00-05',
      '2026-08-28 23:59:59-05',
      true,
      410,
      null,
      null,
      null,
      7,
      'Summer may end, but advocacy does not.',
      '📹',
      'Open Submission Flow',
      'reflection',
      'team_review',
      'Reflection helps members carry the season into sustained advocacy.',
      'submission',
      null,
      true
    ),
    (
      'finish-strong-final-petitions',
      'sign_petition',
      'Encourage People to Sign Final Petitions',
      'Make one final push for the Camp GPE petition actions.',
      'Share one or more final petitions and submit a screenshot, link, or note.',
      'sign_petition',
      2::integer,
      '2026-08-17 00:00:00-05',
      '2026-08-28 23:59:59-05',
      true,
      420,
      'https://www.girlplusenvironment.org/high-energy-bills-action',
      null,
      null,
      7,
      'Summer may end, but advocacy does not.',
      '📣',
      'Open Petition',
      'social_link',
      'team_review',
      'A final push keeps momentum moving after the featured week ends.',
      'petition',
      'https://www.girlplusenvironment.org/high-energy-bills-action',
      false
    ),
    (
      'finish-strong-advocacy-reflection',
      'share_story',
      'Reflect on Your Advocacy Journey',
      'Share how your voice, confidence, or climate advocacy changed during Camp GPE.',
      'Submit a written reflection, video, or social post for Team GPE review.',
      'share_story',
      2::integer,
      '2026-08-17 00:00:00-05',
      '2026-08-28 23:59:59-05',
      true,
      430,
      null,
      null,
      null,
      7,
      'Summer may end, but advocacy does not.',
      '💚',
      'Open Submission Flow',
      'reflection',
      'team_review',
      'Advocacy becomes stronger when members can name what they learned and what they will keep doing.',
      'submission',
      null,
      false
    )
) as seed (
  slug,
  action_type_slug,
  title,
  short_description,
  instructions,
  category,
  point_value,
  starts_at,
  ends_at,
  requires_proof,
  display_order,
  action_url,
  external_source,
  external_action_slug,
  week_number,
  theme,
  icon,
  cta_label,
  submission_type,
  verification_method,
  why_it_matters,
  related_kind,
  related_url,
  is_featured
)
join public.gpe_action_types action_type
  on action_type.slug = seed.action_type_slug
where season.slug = 'camp-gpe-2026'
on conflict (season_id, slug) do update
set
  action_type_id = excluded.action_type_id,
  title = excluded.title,
  short_description = excluded.short_description,
  instructions = excluded.instructions,
  category = excluded.category,
  point_value = excluded.point_value,
  starts_at = excluded.starts_at,
  ends_at = excluded.ends_at,
  is_active = excluded.is_active,
  is_public = excluded.is_public,
  is_hub_visible = excluded.is_hub_visible,
  requires_proof = excluded.requires_proof,
  requires_review = excluded.requires_review,
  auto_approve = excluded.auto_approve,
  allow_multiple_submissions = excluded.allow_multiple_submissions,
  max_completions_per_member = excluded.max_completions_per_member,
  display_order = excluded.display_order,
  action_url = excluded.action_url,
  external_source = excluded.external_source,
  external_action_slug = excluded.external_action_slug,
  week_number = excluded.week_number,
  theme = excluded.theme,
  icon = excluded.icon,
  cta_label = excluded.cta_label,
  submission_type = excluded.submission_type,
  verification_method = excluded.verification_method,
  badge_eligible = excluded.badge_eligible,
  why_it_matters = excluded.why_it_matters,
  related_kind = excluded.related_kind,
  related_url = excluded.related_url,
  is_featured = excluded.is_featured,
  updated_at = now();

update public.gpe_challenges
set
    is_active = false,
    is_hub_visible = false,
    updated_at = now()
where slug in (
    'challenge-1-july-6-17',
    'challenge-2-july-20-31',
    'challenge-3-august-3-14',
    'challenge-4-august-17-28'
)
and exists (
    select 1
    from public.gpe_seasons s
    where s.id = public.gpe_challenges.season_id
      and s.slug = 'camp-gpe-2026'
);

commit;
