alter type public.gpe_action_points_status add value if not exists 'requires_review';

insert into public.hub_point_rules (
  action_type,
  display_name,
  point_value,
  active,
  counts_for_ongoing,
  counts_for_season,
  counts_for_cabin,
  requires_approval,
  max_awards_per_user,
  duplicate_strategy,
  season_override_id,
  lifetime_cap,
  daily_cap,
  duplicate_policy,
  notes,
  metadata
)
values
  (
    'resource_approved',
    'Resource Approved',
    20,
    true,
    true,
    false,
    false,
    true,
    null,
    'source_once',
    null,
    null,
    null,
    'source_once',
    'Awarded when Team GPE approves a member-submitted resource.',
    '{"category":"resources","source":"hub_listing_review","event_type":"RESOURCE_APPROVED","requires_review":true}'::jsonb
  ),
  (
    'job_approved',
    'Job Approved',
    20,
    true,
    true,
    false,
    false,
    true,
    null,
    'source_once',
    null,
    null,
    null,
    'source_once',
    'Awarded when Team GPE approves a member-submitted job listing.',
    '{"category":"jobs","source":"hub_listing_review","event_type":"JOB_APPROVED","requires_review":true}'::jsonb
  ),
  (
    'opportunity_approved',
    'Funding Opportunity Approved',
    20,
    true,
    true,
    false,
    false,
    true,
    null,
    'source_once',
    null,
    null,
    null,
    'source_once',
    'Awarded when Team GPE approves a member-submitted funding opportunity.',
    '{"category":"fundraisers","source":"hub_listing_review","event_type":"OPPORTUNITY_APPROVED","requires_review":true}'::jsonb
  ),
  (
    'event_submitted',
    'Community Event Approved',
    15,
    true,
    true,
    false,
    false,
    true,
    null,
    'source_once',
    null,
    null,
    null,
    'source_once',
    'Awarded when Team GPE approves a member-submitted community event.',
    '{"category":"events","source":"hub_listing_review","event_type":"EVENT_SUBMITTED","requires_review":true}'::jsonb
  ),
  (
    'member_invited',
    'Member Invited',
    5,
    true,
    true,
    false,
    false,
    false,
    10,
    'daily_cap',
    null,
    null,
    10,
    'daily_cap',
    'Awarded when an authenticated Hub user sends a deduplicated member invitation.',
    '{"category":"invitations","source":"hub_invitation","event_type":"MEMBER_INVITED"}'::jsonb
  ),
  (
    'profile_completed',
    'Profile Completed',
    15,
    true,
    true,
    false,
    false,
    false,
    1,
    'source_once',
    null,
    1,
    null,
    'lifetime_cap',
    'Awarded once when a member completes the required Hub profile fields.',
    '{"category":"profile","source":"hub_profile","event_type":"PROFILE_COMPLETED"}'::jsonb
  ),
  (
    'community_post_created',
    'Community Post Created',
    0,
    false,
    true,
    false,
    false,
    true,
    1,
    'daily_cap',
    null,
    null,
    1,
    'daily_cap',
    'Rule placeholder only. Community posts need a moderation/rule decision before points should be awarded.',
    '{"category":"community","source":"hub_post","event_type":"COMMUNITY_POST_CREATED","needs_rule_decision":true}'::jsonb
  ),
  (
    'comment_created',
    'Comment Created',
    0,
    false,
    true,
    false,
    false,
    true,
    5,
    'daily_cap',
    null,
    null,
    5,
    'daily_cap',
    'Rule placeholder only. Comments need a moderation/rule decision before points should be awarded.',
    '{"category":"community","source":"hub_comment","event_type":"COMMENT_CREATED","needs_rule_decision":true}'::jsonb
  )
on conflict (action_type) do update set
  display_name = excluded.display_name,
  point_value = excluded.point_value,
  active = excluded.active,
  counts_for_ongoing = excluded.counts_for_ongoing,
  counts_for_season = excluded.counts_for_season,
  counts_for_cabin = excluded.counts_for_cabin,
  requires_approval = excluded.requires_approval,
  max_awards_per_user = excluded.max_awards_per_user,
  duplicate_strategy = excluded.duplicate_strategy,
  season_override_id = excluded.season_override_id,
  lifetime_cap = excluded.lifetime_cap,
  daily_cap = excluded.daily_cap,
  duplicate_policy = excluded.duplicate_policy,
  notes = excluded.notes,
  metadata = public.hub_point_rules.metadata || excluded.metadata,
  updated_at = now();
